/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeaderboardEntry {
  'totalGesturesLearned' : bigint,
  'displayName' : string,
  'userId' : UserId,
}
export type MarkResult = { 'ok' : UserProfile } |
  { 'err' : string };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'totalGesturesLearned' : bigint,
  'displayName' : string,
  'lastActiveAt' : Timestamp,
  'createdAt' : Timestamp,
  'learnedAlphabets' : Array<string>,
  'learnedNumbers' : Array<string>,
  'learnedCommonGestures' : Array<string>,
}
export interface _SERVICE {
  'getLeaderboardStats' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getOrCreateProfile' : ActorMethod<[], UserProfile>,
  'getProgress' : ActorMethod<[], [] | [UserProfile]>,
  'markGestureLearned' : ActorMethod<[string, string], MarkResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];