/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const LeaderboardEntry = IDL.Record({
  'totalGesturesLearned' : IDL.Nat,
  'displayName' : IDL.Text,
  'userId' : UserId,
});
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'totalGesturesLearned' : IDL.Nat,
  'displayName' : IDL.Text,
  'lastActiveAt' : Timestamp,
  'createdAt' : Timestamp,
  'learnedAlphabets' : IDL.Vec(IDL.Text),
  'learnedNumbers' : IDL.Vec(IDL.Text),
  'learnedCommonGestures' : IDL.Vec(IDL.Text),
});
export const MarkResult = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getLeaderboardStats' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getOrCreateProfile' : IDL.Func([], [UserProfile], []),
  'getProgress' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'markGestureLearned' : IDL.Func([IDL.Text, IDL.Text], [MarkResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const LeaderboardEntry = IDL.Record({
    'totalGesturesLearned' : IDL.Nat,
    'displayName' : IDL.Text,
    'userId' : UserId,
  });
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'totalGesturesLearned' : IDL.Nat,
    'displayName' : IDL.Text,
    'lastActiveAt' : Timestamp,
    'createdAt' : Timestamp,
    'learnedAlphabets' : IDL.Vec(IDL.Text),
    'learnedNumbers' : IDL.Vec(IDL.Text),
    'learnedCommonGestures' : IDL.Vec(IDL.Text),
  });
  const MarkResult = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  
  return IDL.Service({
    'getLeaderboardStats' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getOrCreateProfile' : IDL.Func([], [UserProfile], []),
    'getProgress' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'markGestureLearned' : IDL.Func([IDL.Text, IDL.Text], [MarkResult], []),
  });
};

export const init = ({ IDL }) => { return []; };